// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mimaiunubotyfoljosed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pbWFpdW51Ym90eWZvbGpvc2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MzA3NjIsImV4cCI6MjA1NDIwNjc2Mn0.y8ABMKWi-u07Xh1h-9hYYER6m0mNE_R0wJ2pGzEayeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);